"""
Shared helpers for the NIGHTCELL 7 Blender asset generators.

Every model in this game is generated by a script, never modelled by hand.
That is a hard requirement, not a stylistic one: CLAUDE.md forbids shipping any
asset without provenance, and a committed generator script is the strongest
provenance there is — the asset can be rebuilt from a commit, and a reviewer
can read exactly how it was made.

Three rules hold everywhere in this package:

 1. **One Blender metre is one game metre.** No import scaling, no "fix it in
    the engine". The collision volumes in `@nightcell7/multiplayer-sim` are in
    metres and the art has to agree with them.
 2. **Deterministic.** All randomness comes from a seeded generator, so
    `git checkout && pnpm assets:build` reproduces the same mesh. An asset that
    changes every build cannot be reviewed.
 3. **No embedded textures.** Meshes carry UVs and a *named* material slot.
    Babylon binds the real PBR maps by that name at load time. Embedding them
    per-GLB would ship the same steel texture a dozen times and blow the 15 MB
    shell budget (PRD §30).
"""

from __future__ import annotations

import math
import os
import random
import sys
from dataclasses import dataclass

import bmesh
import bpy
from mathutils import Vector

# Material slot names. These are the contract with the engine: `world.ts` looks
# materials up by exactly these strings, so renaming one here silently
# un-skins every mesh that used it.
MAT_CONCRETE = "concrete"
MAT_STEEL = "steel"
MAT_RUST = "rust"
MAT_PAINT_RED = "paint_red"
MAT_PAINT_CYAN = "paint_cyan"
MAT_GRATING = "grating"
MAT_GLASS_EMISSIVE = "lamp_glass"
MAT_RUBBER = "rubber"

ALL_MATERIALS = (
    MAT_CONCRETE,
    MAT_STEEL,
    MAT_RUST,
    MAT_PAINT_RED,
    MAT_PAINT_CYAN,
    MAT_GRATING,
    MAT_GLASS_EMISSIVE,
    MAT_RUBBER,
)

# Approximate viewer-facing colours, used only as the glTF baseColorFactor so a
# model is not black in a generic glTF viewer. The engine overrides these.
_MATERIAL_TINT = {
    MAT_CONCRETE: (0.19, 0.20, 0.21, 1.0),
    MAT_STEEL: (0.26, 0.28, 0.31, 1.0),
    MAT_RUST: (0.35, 0.21, 0.14, 1.0),
    MAT_PAINT_RED: (0.70, 0.19, 0.21, 1.0),
    MAT_PAINT_CYAN: (0.23, 0.52, 0.55, 1.0),
    MAT_GRATING: (0.22, 0.24, 0.26, 1.0),
    MAT_GLASS_EMISSIVE: (1.0, 0.71, 0.36, 1.0),
    MAT_RUBBER: (0.06, 0.06, 0.07, 1.0),
}

_MATERIAL_SURFACE = {
    # (metallic, roughness)
    MAT_CONCRETE: (0.0, 0.88),
    MAT_STEEL: (0.85, 0.42),
    MAT_RUST: (0.35, 0.78),
    MAT_PAINT_RED: (0.15, 0.62),
    MAT_PAINT_CYAN: (0.15, 0.62),
    MAT_GRATING: (0.80, 0.50),
    MAT_GLASS_EMISSIVE: (0.0, 0.30),
    MAT_RUBBER: (0.0, 0.94),
}

# Texel density, in texels per metre, used when UV-unwrapping by box
# projection. One number everywhere is what makes surfaces look like they
# belong in the same world — mismatched density is the single most obvious
# "amateur" tell in a 3D scene.
TEXELS_PER_METRE = 128.0
_UV_SCALE = 1.0 / 4.0  # one texture tile spans 4 m


# ---------------------------------------------------------------- scene setup


def reset_scene() -> None:
    """Start from a genuinely empty file so generators cannot leak into each other."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0


def rng(seed: int) -> random.Random:
    """Seeded RNG. Never use the module-level `random` in a generator."""
    return random.Random(seed)


# ---------------------------------------------------------------- materials


def get_material(name: str) -> bpy.types.Material:
    """Fetch or create the shared material named `name`."""
    if name in bpy.data.materials:
        return bpy.data.materials[name]

    material = bpy.data.materials.new(name)
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        metallic, roughness = _MATERIAL_SURFACE.get(name, (0.0, 0.8))
        bsdf.inputs["Base Color"].default_value = _MATERIAL_TINT.get(name, (0.5, 0.5, 0.5, 1.0))
        bsdf.inputs["Metallic"].default_value = metallic
        bsdf.inputs["Roughness"].default_value = roughness
        if name == MAT_GLASS_EMISSIVE:
            bsdf.inputs["Emission Color"].default_value = _MATERIAL_TINT[name]
            bsdf.inputs["Emission Strength"].default_value = 4.0
    return material


# ------------------------------------------------------------------- meshes


@dataclass
class Part:
    """A finished bmesh ready to be merged into an object under one material."""

    bm: bmesh.types.BMesh
    material: str


def new_bmesh() -> bmesh.types.BMesh:
    return bmesh.new()


def add_box(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    size: tuple[float, float, float],
    rotation_z: float = 0.0,
) -> list[bmesh.types.BMFace]:
    """Axis-aligned (optionally Z-rotated) box, sized in metres."""
    from mathutils import Matrix

    result = bmesh.ops.create_cube(bm, size=1.0)
    verts = result["verts"]

    matrix = (
        Matrix.Translation(Vector(centre))
        @ Matrix.Rotation(rotation_z, 4, "Z")
        @ Matrix.Diagonal(Vector(size)).to_4x4()
    )
    bmesh.ops.transform(bm, matrix=matrix, verts=verts)

    faces: list[bmesh.types.BMFace] = []
    for vert in verts:
        faces.extend(vert.link_faces)
    return list(dict.fromkeys(faces))


def add_cylinder(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    radius: float,
    height: float,
    segments: int = 16,
    axis: str = "Z",
    cap: bool = True,
) -> None:
    from mathutils import Matrix

    result = bmesh.ops.create_cone(
        bm,
        cap_ends=cap,
        cap_tris=False,
        segments=segments,
        radius1=radius,
        radius2=radius,
        depth=height,
    )
    verts = result["verts"]

    rotation = Matrix.Identity(4)
    if axis == "X":
        rotation = Matrix.Rotation(math.radians(90), 4, "Y")
    elif axis == "Y":
        rotation = Matrix.Rotation(math.radians(90), 4, "X")

    bmesh.ops.transform(
        bm, matrix=Matrix.Translation(Vector(centre)) @ rotation, verts=verts
    )


def add_tube(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    radius: float,
    height: float,
    segments: int = 16,
    axis: str = "Z",
) -> None:
    """Open-ended cylinder — cheaper than a capped one where the ends never show."""
    add_cylinder(bm, centre, radius, height, segments=segments, axis=axis, cap=False)


def bevel(bm: bmesh.types.BMesh, width: float = 0.01, segments: int = 1) -> None:
    """
    Bevel every edge.

    Small bevels are the difference between "3D model" and "programmer box":
    they catch a specular highlight along each edge, which is what tells the eye
    an object is solid. 1 cm is enough at yard scale and costs few triangles.
    """
    bmesh.ops.bevel(
        bm,
        geom=list(bm.verts) + list(bm.edges) + list(bm.faces),
        offset=width,
        segments=segments,
        profile=0.5,
        affect="EDGES",
        clamp_overlap=True,
    )


# ----------------------------------------------------------------------- UVs


def box_unwrap(bm: bmesh.types.BMesh, scale: float = _UV_SCALE) -> None:
    """
    Planar-project each face along its dominant axis.

    Cheap, seam-free enough for tiling industrial materials, and — unlike
    Blender's Smart UV Project — completely deterministic, which the
    reproducibility rule requires.
    """
    uv_layer = bm.loops.layers.uv.verify()

    for face in bm.faces:
        normal = face.normal
        ax, ay, az = abs(normal.x), abs(normal.y), abs(normal.z)

        for loop in face.loops:
            position = loop.vert.co
            if az >= ax and az >= ay:
                u, v = position.x, position.y
            elif ax >= ay:
                u, v = position.y, position.z
            else:
                u, v = position.x, position.z
            loop[uv_layer].uv = (u * scale, v * scale)


# -------------------------------------------------------------------- object


def finish_object(name: str, parts: list[Part], shade_smooth_angle: float | None = None):
    """
    Merge `parts` into one mesh object, one material slot per distinct material.

    Merging matters for draw calls: the yard places dozens of these, and a prop
    split across six objects is six draw calls every frame instead of one.
    """
    mesh = bpy.data.meshes.new(name)
    merged = bmesh.new()

    materials: list[str] = []
    for part in parts:
        if part.material not in materials:
            materials.append(part.material)

    for part in parts:
        index = materials.index(part.material)
        box_unwrap(part.bm)

        # Copy the part into the merged mesh, tagging faces with their slot.
        temp = bpy.data.meshes.new(f"{name}_tmp")
        part.bm.to_mesh(temp)
        part.bm.free()

        scratch = bmesh.new()
        scratch.from_mesh(temp)
        for face in scratch.faces:
            face.material_index = index
        scratch.to_mesh(temp)
        scratch.free()

        merged.from_mesh(temp)
        bpy.data.meshes.remove(temp)

    bmesh.ops.remove_doubles(merged, verts=list(merged.verts), dist=0.0001)

    if shade_smooth_angle is not None:
        # Angle-based smoothing done in bmesh, not with an operator.
        #
        # `bpy.ops.object.shade_auto_smooth` needs a UI context and silently
        # fails in --background. The previous version set every polygon smooth
        # and relied on that operator to re-sharpen the hard edges; when it
        # failed, cylinders ended up fully smooth and their end caps blended
        # into the sides, so every pipe and vessel rendered with rounded,
        # ball-like ends.
        #
        # Since Blender 4.1, marking an edge sharp is exactly how auto-smooth
        # is expressed, so doing it directly is both correct and deterministic.
        for face in merged.faces:
            face.smooth = True
        for edge in merged.edges:
            if len(edge.link_faces) == 2 and edge.calc_face_angle(0.0) > shade_smooth_angle:
                edge.smooth = False

    merged.to_mesh(mesh)
    merged.free()

    for material_name in materials:
        mesh.materials.append(get_material(material_name))

    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def add_collider(name: str, centre: tuple[float, float, float], size: tuple[float, float, float]):
    """
    Add a `COL_`-prefixed collision proxy (CLAUDE.md).

    Exported alongside the visual mesh so the engine — or a future physics
    pass — can use a cheap box hull instead of the render geometry.
    """
    bm = bmesh.new()
    add_box(bm, centre, size)
    mesh = bpy.data.meshes.new(f"COL_{name}")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(f"COL_{name}", mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def add_socket(name: str, location: tuple[float, float, float], rotation=(0.0, 0.0, 0.0)):
    """Add a `SOCKET_`-prefixed empty — attachment points such as SOCKET_MUZZLE."""
    empty = bpy.data.objects.new(f"SOCKET_{name}", None)
    empty.empty_display_type = "ARROWS"
    empty.empty_display_size = 0.1
    empty.location = location
    empty.rotation_euler = rotation
    bpy.context.collection.objects.link(empty)
    return empty


# ------------------------------------------------------------------- export


def export_glb(path: str, *, animated: bool = False) -> None:
    """
    Export the whole scene to GLB, without textures or lights.

    `animated` turns on skinning and animation export. It is off by default
    because the props have neither, and exporting empty skin/animation blocks
    on every static mesh is wasted bytes.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        export_apply=True,
        export_yup=True,
        # No images: materials are bound by name in the engine.
        export_materials="EXPORT",
        export_image_format="NONE",
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_animations=animated,
        # Each action becomes its own glTF animation, which is what Babylon
        # loads as a separate AnimationGroup.
        export_animation_mode="ACTIONS" if animated else "ACTIONS",
        export_bake_animation=animated,
        export_skins=animated,
        export_morph=False,
        # Empties carry the SOCKET_ markers, so they must survive the export.
        use_visible=False,
        use_renderable=False,
        export_texcoords=True,
        export_normals=True,
        export_tangents=False,
    )

    size = os.path.getsize(path)
    tris = sum(
        len(o.data.loop_triangles)
        for o in bpy.data.objects
        if o.type == "MESH" and (o.data.calc_loop_triangles() or True)
    )
    print(f"EXPORTED {os.path.basename(path)} bytes={size} tris={tris}")


def output_path(filename: str) -> str:
    """Resolve an output path from `--output <dir>` on the Blender command line."""
    argv = sys.argv
    if "--output" in argv:
        base = argv[argv.index("--output") + 1]
    else:
        base = os.path.join(os.path.dirname(__file__), "..", "..", "..", "build", "models")
    return os.path.abspath(os.path.join(base, filename))


# ------------------------------------------------------------------ lofting

def ring(
    centre: tuple[float, float, float],
    rx: float,
    ry: float,
    segments: int = 12,
    squash: float = 0.0,
    rotation: float = 0.0,
) -> list[Vector]:
    """
    One cross-section: an ellipse, optionally squared off toward a rectangle.

    `squash` blends from a true ellipse (0) toward a rounded rectangle (1).
    Bodies are not circular in section — a chest is broad and flat, a forearm
    is nearly round — and that difference is most of what separates a lofted
    figure from a stack of cylinders.
    """
    points: list[Vector] = []
    for i in range(segments):
        a = rotation + (i / segments) * math.tau
        c, s = math.cos(a), math.sin(a)
        # Superellipse-ish: push the point outward toward the bounding box.
        if squash > 0.0:
            m = max(abs(c), abs(s))
            c = c * (1 - squash) + (c / m) * squash
            s = s * (1 - squash) + (s / m) * squash
        points.append(Vector((centre[0] + c * rx, centre[1] + s * ry, centre[2])))
    return points


def loft(bm: bmesh.types.BMesh, rings: list[list[Vector]], cap: bool = True) -> None:
    """
    Bridge a sequence of equal-length rings into a tube.

    This is the core of the character work. Stacking primitives gives a figure
    made of visible blocks no amount of texturing hides; lofting a profile that
    changes along its length gives limbs that taper and a torso that actually
    has a waist.
    """
    if len(rings) < 2:
        return

    verts = [[bm.verts.new(p) for p in r] for r in rings]

    for a, b in zip(verts, verts[1:]):
        n = len(a)
        for i in range(n):
            j = (i + 1) % n
            try:
                bm.faces.new((a[i], a[j], b[j], b[i]))
            except ValueError:
                # Duplicate face where two rings coincide; harmless.
                pass

    if cap:
        for end in (verts[0], verts[-1]):
            try:
                bm.faces.new(end)
            except ValueError:
                pass

    bm.verts.index_update()
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])


def limb(
    bm: bmesh.types.BMesh,
    joints: list[tuple[tuple[float, float, float], float, float]],
    segments: int = 10,
    squash: float = 0.0,
) -> None:
    """
    Loft a limb through `(centre, rx, ry)` joints.

    Rings are oriented in the XY plane and stacked in Z, which suits a figure
    modelled standing in a neutral pose — every limb here runs broadly
    vertically, and the rig bends them later.
    """
    loft(bm, [ring(c, rx, ry, segments, squash) for c, rx, ry in joints])


def subdivide_smooth(bm: bmesh.types.BMesh, cuts: int = 1) -> None:
    """
    Catmull-Clark-ish smoothing pass.

    Applied to the body only. Gear stays faceted: hard surfaces should read as
    hard, and smoothing a plate carrier makes it look inflated.
    """
    for _ in range(cuts):
        bmesh.ops.subdivide_edges(
            bm,
            edges=bm.edges[:],
            cuts=1,
            use_grid_fill=True,
            smooth=1.0,
        )


# -------------------------------------------------------------------- rigging

# The skeleton, as (name, parent, head, tail). Positions match the proportions
# in `character.py`; if that file's joints move, these must follow.
HUMANOID_BONES = [
    ("hips",        None,        (0.000,  0.000, 0.920), (0.000,  0.000, 1.030)),
    ("spine",       "hips",      (0.000,  0.000, 1.030), (0.000,  0.000, 1.170)),
    ("chest",       "spine",     (0.000,  0.000, 1.170), (0.000,  0.000, 1.330)),
    ("neck",        "chest",     (0.000,  0.000, 1.330), (0.000,  0.000, 1.470)),
    ("head",        "neck",      (0.000,  0.000, 1.470), (0.000,  0.000, 1.760)),

    ("shoulder.L", "chest",  (0.060, 0.0, 1.320), ( 0.200, 0.0, 1.350)),
    ("upperarm.L", "shoulder.L", ( 0.200, 0.000, 1.350), ( 0.225, -0.010, 1.100)),
    ("forearm.L",  "upperarm.L", ( 0.225, -0.010, 1.100), ( 0.205, -0.150, 0.945)),
    ("hand.L",     "forearm.L",  ( 0.205, -0.150, 0.945), ( 0.190, -0.260, 0.940)),

    ("shoulder.R", "chest",  (-0.060, 0.0, 1.320), (-0.200, 0.0, 1.350)),
    ("upperarm.R", "shoulder.R", (-0.200, 0.000, 1.350), (-0.225, -0.010, 1.100)),
    ("forearm.R",  "upperarm.R", (-0.225, -0.010, 1.100), (-0.205, -0.150, 0.945)),
    ("hand.R",     "forearm.R",  (-0.205, -0.150, 0.945), (-0.190, -0.260, 0.940)),

    ("thigh.L", "hips",    ( 0.098, 0.000, 0.920), ( 0.098, 0.000, 0.450)),
    ("shin.L",  "thigh.L", ( 0.098, 0.000, 0.450), ( 0.098, 0.000, 0.100)),
    ("foot.L",  "shin.L",  ( 0.098, 0.000, 0.100), ( 0.098, -0.140, 0.020)),

    ("thigh.R", "hips",    (-0.098, 0.000, 0.920), (-0.098, 0.000, 0.450)),
    ("shin.R",  "thigh.R", (-0.098, 0.000, 0.450), (-0.098, 0.000, 0.100)),
    ("foot.R",  "shin.R",  (-0.098, 0.000, 0.100), (-0.098, -0.140, 0.020)),
]


def build_armature(name: str = "rig"):
    """Create the humanoid armature in the current scene."""
    armature = bpy.data.armatures.new(name)
    obj = bpy.data.objects.new(name, armature)
    bpy.context.collection.objects.link(obj)

    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")

    for bone_name, parent, head, tail in HUMANOID_BONES:
        bone = armature.edit_bones.new(bone_name)
        bone.head = Vector(head)
        bone.tail = Vector(tail)
        if parent:
            bone.parent = armature.edit_bones[parent]
            bone.use_connect = False

    bpy.ops.object.mode_set(mode="OBJECT")
    return obj


def _point_segment_distance(p: Vector, a: Vector, b: Vector) -> float:
    ab = b - a
    length_sq = ab.dot(ab)
    if length_sq < 1e-12:
        return (p - a).length
    t = max(0.0, min(1.0, (p - a).dot(ab) / length_sq))
    return (p - (a + ab * t)).length


def bind_by_proximity(mesh_obj, armature_obj, blend: float = 0.035) -> None:
    """
    Weight every vertex to its nearest bone, blending with the runner-up.

    Blender's automatic (bone-heat) weighting is the usual choice and it fails
    here: this mesh is a union of many disjoint pieces — pouches, straps, boots
    — and bone heat needs closed, connected geometry, so it errors out on
    "failed to find solution for one or more bones".

    Nearest-segment weighting is robust against any topology because it only
    looks at distance. Blending the two closest bones over a few centimetres
    keeps elbows and knees from tearing into rigid chunks, which is the usual
    complaint about this approach.
    """
    bones = [
        (b.name, armature_obj.matrix_world @ b.head_local, armature_obj.matrix_world @ b.tail_local)
        for b in armature_obj.data.bones
    ]

    groups = {name: mesh_obj.vertex_groups.new(name=name) for name, _, _ in bones}

    for vertex in mesh_obj.data.vertices:
        world = mesh_obj.matrix_world @ vertex.co
        ranked = sorted(
            ((_point_segment_distance(world, head, tail), name) for name, head, tail in bones),
            key=lambda pair: pair[0],
        )
        best_d, best = ranked[0]
        second_d, second = ranked[1] if len(ranked) > 1 else (best_d, best)

        if second_d - best_d >= blend:
            groups[best].add([vertex.index], 1.0, "REPLACE")
        else:
            # Linear blend across the overlap band.
            t = 0.5 + (second_d - best_d) / (2.0 * blend)
            groups[best].add([vertex.index], t, "REPLACE")
            groups[second].add([vertex.index], 1.0 - t, "REPLACE")

    mesh_obj.parent = armature_obj
    modifier = mesh_obj.modifiers.new("Armature", "ARMATURE")
    modifier.object = armature_obj


# ------------------------------------------------------------------ animation


def new_action(armature_obj, name: str):
    """Start a fresh action on the armature and return it."""
    if armature_obj.animation_data is None:
        armature_obj.animation_data_create()
    action = bpy.data.actions.new(name)
    # Without a fake user an unassigned action is dropped before export.
    action.use_fake_user = True
    armature_obj.animation_data.action = action
    for pose_bone in armature_obj.pose.bones:
        pose_bone.rotation_mode = "XYZ"
    return action


def key_pose(armature_obj, frame: int, pose: dict) -> None:
    """
    Key a set of bone rotations (degrees) at `frame`.

    Every bone named in the action is keyed on every keyframe, even when it is
    not moving. glTF samples animation per channel, and a bone keyed on only
    some frames interpolates from wherever it happened to be — which shows up
    as limbs drifting between cycles.
    """
    for bone_name, rotation in pose.items():
        pose_bone = armature_obj.pose.bones.get(bone_name)
        if pose_bone is None:
            continue
        pose_bone.rotation_euler = tuple(math.radians(a) for a in rotation)
        pose_bone.keyframe_insert("rotation_euler", frame=frame)


def key_location(armature_obj, bone_name: str, frame: int, offset) -> None:
    pose_bone = armature_obj.pose.bones.get(bone_name)
    if pose_bone is None:
        return
    pose_bone.location = Vector(offset)
    pose_bone.keyframe_insert("location", frame=frame)


def set_action_range(action, start: int, end: int) -> None:
    action.frame_range  # noqa: B018 - touch so Blender computes it
    action.use_frame_range = True
    action.frame_start = start
    action.frame_end = end
