"""
Shared helpers for the NIGHTCELL 7 Blender asset generators.

Every model in this game is generated by a script, never modelled by hand.
That is a hard requirement, not a stylistic one: CLAUDE.md forbids shipping any
asset without provenance, and a committed generator script is the strongest
provenance there is — the asset can be rebuilt from a commit, and a reviewer
can read exactly how it was made.

Three rules hold everywhere in this package:

 1. **One Blender metre is one game metre.** No import scaling, no "fix it in
    the engine". The collision volumes in `@nightcell7/multiplayer-sim` are in
    metres and the art has to agree with them.
 2. **Deterministic.** All randomness comes from a seeded generator, so
    `git checkout && pnpm assets:build` reproduces the same mesh. An asset that
    changes every build cannot be reviewed.
 3. **No embedded textures.** Meshes carry UVs and a *named* material slot.
    Babylon binds the real PBR maps by that name at load time. Embedding them
    per-GLB would ship the same steel texture a dozen times and blow the 15 MB
    shell budget (PRD §30).
"""

from __future__ import annotations

import math
import os
import random
import sys
from dataclasses import dataclass

import bmesh
import bpy
from mathutils import Vector

# Material slot names. These are the contract with the engine: `world.ts` looks
# materials up by exactly these strings, so renaming one here silently
# un-skins every mesh that used it.
MAT_CONCRETE = "concrete"
MAT_STEEL = "steel"
MAT_RUST = "rust"
MAT_PAINT_RED = "paint_red"
MAT_PAINT_CYAN = "paint_cyan"
MAT_GRATING = "grating"
MAT_GLASS_EMISSIVE = "lamp_glass"
MAT_RUBBER = "rubber"

ALL_MATERIALS = (
    MAT_CONCRETE,
    MAT_STEEL,
    MAT_RUST,
    MAT_PAINT_RED,
    MAT_PAINT_CYAN,
    MAT_GRATING,
    MAT_GLASS_EMISSIVE,
    MAT_RUBBER,
)

# Approximate viewer-facing colours, used only as the glTF baseColorFactor so a
# model is not black in a generic glTF viewer. The engine overrides these.
_MATERIAL_TINT = {
    MAT_CONCRETE: (0.19, 0.20, 0.21, 1.0),
    MAT_STEEL: (0.26, 0.28, 0.31, 1.0),
    MAT_RUST: (0.35, 0.21, 0.14, 1.0),
    MAT_PAINT_RED: (0.70, 0.19, 0.21, 1.0),
    MAT_PAINT_CYAN: (0.23, 0.52, 0.55, 1.0),
    MAT_GRATING: (0.22, 0.24, 0.26, 1.0),
    MAT_GLASS_EMISSIVE: (1.0, 0.71, 0.36, 1.0),
    MAT_RUBBER: (0.06, 0.06, 0.07, 1.0),
}

_MATERIAL_SURFACE = {
    # (metallic, roughness)
    MAT_CONCRETE: (0.0, 0.88),
    MAT_STEEL: (0.85, 0.42),
    MAT_RUST: (0.35, 0.78),
    MAT_PAINT_RED: (0.15, 0.62),
    MAT_PAINT_CYAN: (0.15, 0.62),
    MAT_GRATING: (0.80, 0.50),
    MAT_GLASS_EMISSIVE: (0.0, 0.30),
    MAT_RUBBER: (0.0, 0.94),
}

# Texel density, in texels per metre, used when UV-unwrapping by box
# projection. One number everywhere is what makes surfaces look like they
# belong in the same world — mismatched density is the single most obvious
# "amateur" tell in a 3D scene.
TEXELS_PER_METRE = 128.0
_UV_SCALE = 1.0 / 4.0  # one texture tile spans 4 m


# ---------------------------------------------------------------- scene setup


def reset_scene() -> None:
    """Start from a genuinely empty file so generators cannot leak into each other."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0


def rng(seed: int) -> random.Random:
    """Seeded RNG. Never use the module-level `random` in a generator."""
    return random.Random(seed)


# ---------------------------------------------------------------- materials


def get_material(name: str) -> bpy.types.Material:
    """Fetch or create the shared material named `name`."""
    if name in bpy.data.materials:
        return bpy.data.materials[name]

    material = bpy.data.materials.new(name)
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        metallic, roughness = _MATERIAL_SURFACE.get(name, (0.0, 0.8))
        bsdf.inputs["Base Color"].default_value = _MATERIAL_TINT.get(name, (0.5, 0.5, 0.5, 1.0))
        bsdf.inputs["Metallic"].default_value = metallic
        bsdf.inputs["Roughness"].default_value = roughness
        if name == MAT_GLASS_EMISSIVE:
            bsdf.inputs["Emission Color"].default_value = _MATERIAL_TINT[name]
            bsdf.inputs["Emission Strength"].default_value = 4.0
    return material


# ------------------------------------------------------------------- meshes


@dataclass
class Part:
    """A finished bmesh ready to be merged into an object under one material."""

    bm: bmesh.types.BMesh
    material: str


def new_bmesh() -> bmesh.types.BMesh:
    return bmesh.new()


def add_box(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    size: tuple[float, float, float],
    rotation_z: float = 0.0,
) -> list[bmesh.types.BMFace]:
    """Axis-aligned (optionally Z-rotated) box, sized in metres."""
    from mathutils import Matrix

    result = bmesh.ops.create_cube(bm, size=1.0)
    verts = result["verts"]

    matrix = (
        Matrix.Translation(Vector(centre))
        @ Matrix.Rotation(rotation_z, 4, "Z")
        @ Matrix.Diagonal(Vector(size)).to_4x4()
    )
    bmesh.ops.transform(bm, matrix=matrix, verts=verts)

    faces: list[bmesh.types.BMFace] = []
    for vert in verts:
        faces.extend(vert.link_faces)
    return list(dict.fromkeys(faces))


def add_cylinder(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    radius: float,
    height: float,
    segments: int = 16,
    axis: str = "Z",
    cap: bool = True,
) -> None:
    from mathutils import Matrix

    result = bmesh.ops.create_cone(
        bm,
        cap_ends=cap,
        cap_tris=False,
        segments=segments,
        radius1=radius,
        radius2=radius,
        depth=height,
    )
    verts = result["verts"]

    rotation = Matrix.Identity(4)
    if axis == "X":
        rotation = Matrix.Rotation(math.radians(90), 4, "Y")
    elif axis == "Y":
        rotation = Matrix.Rotation(math.radians(90), 4, "X")

    bmesh.ops.transform(
        bm, matrix=Matrix.Translation(Vector(centre)) @ rotation, verts=verts
    )


def add_tube(
    bm: bmesh.types.BMesh,
    centre: tuple[float, float, float],
    radius: float,
    height: float,
    segments: int = 16,
    axis: str = "Z",
) -> None:
    """Open-ended cylinder — cheaper than a capped one where the ends never show."""
    add_cylinder(bm, centre, radius, height, segments=segments, axis=axis, cap=False)


def bevel(bm: bmesh.types.BMesh, width: float = 0.01, segments: int = 1) -> None:
    """
    Bevel every edge.

    Small bevels are the difference between "3D model" and "programmer box":
    they catch a specular highlight along each edge, which is what tells the eye
    an object is solid. 1 cm is enough at yard scale and costs few triangles.
    """
    bmesh.ops.bevel(
        bm,
        geom=list(bm.verts) + list(bm.edges) + list(bm.faces),
        offset=width,
        segments=segments,
        profile=0.5,
        affect="EDGES",
        clamp_overlap=True,
    )


# ----------------------------------------------------------------------- UVs


def box_unwrap(bm: bmesh.types.BMesh, scale: float = _UV_SCALE) -> None:
    """
    Planar-project each face along its dominant axis.

    Cheap, seam-free enough for tiling industrial materials, and — unlike
    Blender's Smart UV Project — completely deterministic, which the
    reproducibility rule requires.
    """
    uv_layer = bm.loops.layers.uv.verify()

    for face in bm.faces:
        normal = face.normal
        ax, ay, az = abs(normal.x), abs(normal.y), abs(normal.z)

        for loop in face.loops:
            position = loop.vert.co
            if az >= ax and az >= ay:
                u, v = position.x, position.y
            elif ax >= ay:
                u, v = position.y, position.z
            else:
                u, v = position.x, position.z
            loop[uv_layer].uv = (u * scale, v * scale)


# -------------------------------------------------------------------- object


def finish_object(name: str, parts: list[Part], shade_smooth_angle: float | None = None):
    """
    Merge `parts` into one mesh object, one material slot per distinct material.

    Merging matters for draw calls: the yard places dozens of these, and a prop
    split across six objects is six draw calls every frame instead of one.
    """
    mesh = bpy.data.meshes.new(name)
    merged = bmesh.new()

    materials: list[str] = []
    for part in parts:
        if part.material not in materials:
            materials.append(part.material)

    for part in parts:
        index = materials.index(part.material)
        box_unwrap(part.bm)

        # Copy the part into the merged mesh, tagging faces with their slot.
        temp = bpy.data.meshes.new(f"{name}_tmp")
        part.bm.to_mesh(temp)
        part.bm.free()

        scratch = bmesh.new()
        scratch.from_mesh(temp)
        for face in scratch.faces:
            face.material_index = index
        scratch.to_mesh(temp)
        scratch.free()

        merged.from_mesh(temp)
        bpy.data.meshes.remove(temp)

    bmesh.ops.remove_doubles(merged, verts=list(merged.verts), dist=0.0001)

    if shade_smooth_angle is not None:
        # Angle-based smoothing done in bmesh, not with an operator.
        #
        # `bpy.ops.object.shade_auto_smooth` needs a UI context and silently
        # fails in --background. The previous version set every polygon smooth
        # and relied on that operator to re-sharpen the hard edges; when it
        # failed, cylinders ended up fully smooth and their end caps blended
        # into the sides, so every pipe and vessel rendered with rounded,
        # ball-like ends.
        #
        # Since Blender 4.1, marking an edge sharp is exactly how auto-smooth
        # is expressed, so doing it directly is both correct and deterministic.
        for face in merged.faces:
            face.smooth = True
        for edge in merged.edges:
            if len(edge.link_faces) == 2 and edge.calc_face_angle(0.0) > shade_smooth_angle:
                edge.smooth = False

    merged.to_mesh(mesh)
    merged.free()

    for material_name in materials:
        mesh.materials.append(get_material(material_name))

    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def add_collider(name: str, centre: tuple[float, float, float], size: tuple[float, float, float]):
    """
    Add a `COL_`-prefixed collision proxy (CLAUDE.md).

    Exported alongside the visual mesh so the engine — or a future physics
    pass — can use a cheap box hull instead of the render geometry.
    """
    bm = bmesh.new()
    add_box(bm, centre, size)
    mesh = bpy.data.meshes.new(f"COL_{name}")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(f"COL_{name}", mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def add_socket(name: str, location: tuple[float, float, float], rotation=(0.0, 0.0, 0.0)):
    """Add a `SOCKET_`-prefixed empty — attachment points such as SOCKET_MUZZLE."""
    empty = bpy.data.objects.new(f"SOCKET_{name}", None)
    empty.empty_display_type = "ARROWS"
    empty.empty_display_size = 0.1
    empty.location = location
    empty.rotation_euler = rotation
    bpy.context.collection.objects.link(empty)
    return empty


# ------------------------------------------------------------------- export


def export_glb(path: str) -> None:
    """Export the whole scene to GLB, without textures or lights."""
    os.makedirs(os.path.dirname(path), exist_ok=True)

    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        export_apply=True,
        export_yup=True,
        # No images: materials are bound by name in the engine.
        export_materials="EXPORT",
        export_image_format="NONE",
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_animations=False,
        export_skins=False,
        export_morph=False,
        # Empties carry the SOCKET_ markers, so they must survive the export.
        use_visible=False,
        use_renderable=False,
        export_texcoords=True,
        export_normals=True,
        export_tangents=False,
    )

    size = os.path.getsize(path)
    tris = sum(
        len(o.data.loop_triangles)
        for o in bpy.data.objects
        if o.type == "MESH" and (o.data.calc_loop_triangles() or True)
    )
    print(f"EXPORTED {os.path.basename(path)} bytes={size} tris={tris}")


def output_path(filename: str) -> str:
    """Resolve an output path from `--output <dir>` on the Blender command line."""
    argv = sys.argv
    if "--output" in argv:
        base = argv[argv.index("--output") + 1]
    else:
        base = os.path.join(os.path.dirname(__file__), "..", "..", "..", "build", "models")
    return os.path.abspath(os.path.join(base, filename))
