/**
 * Game audio.
 *
 * The build shipped completely silent — no clips, no code. Everything played
 * here is generated by `tools/art/audio/generate.py`; see
 * `apps/game/public/audio/PROVENANCE.md`.
 *
 * Raw Web Audio rather than Babylon's `Sound`: this needs a handful of
 * one-shots, a loop, and a gain trim, and going direct avoids pulling in
 * Babylon's audio engine and its own unlock handling on top of the browser's.
 *
 * Two browser realities shape the design:
 *
 *  1. **Autoplay policy.** An `AudioContext` created before a user gesture
 *     starts suspended, and buffers played into it are silently discarded —
 *     not an error, just nothing. `unlock()` is called from the same gesture
 *     that takes pointer lock.
 *  2. **Decoding is async and not free.** Every clip is fetched and decoded
 *     once up front; triggering a sound mid-match is then a buffer-source
 *     allocation, which is cheap enough to do on every footstep.
 */

/** Clip families with variations. Index is 1-based to match the filenames. */
const VARIED = {
  fire: 4,
  step_concrete: 5,
  step_grating: 4,
  impact_concrete: 4,
} as const;

const SINGLE = ["reload", "ui_hover", "ui_click", "ui_error", "ambience_yard"] as const;

type VariedName = keyof typeof VARIED;

const BASE = `${import.meta.env.BASE_URL}audio/`;

/**
 * Metres of travel between footsteps.
 *
 * Driving steps off distance rather than a timer means they automatically
 * speed up when sprinting and stop when the player does, with no state machine
 * and no drift between the sound and the movement the server simulates.
 */
const STEP_DISTANCE = 2.1;

export interface AudioOptions {
  /** Master trim, 0..1. */
  volume?: number;
}

export class GameAudio {
  private readonly context: AudioContext;
  private readonly master: GainNode;
  private readonly buffers = new Map<string, AudioBuffer>();
  private ambience: AudioBufferSourceNode | null = null;
  private stepAccumulator = 0;
  private lastVariation = new Map<string, number>();
  private ready = false;

  constructor(options: AudioOptions = {}) {
    const Ctor: typeof AudioContext =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
    this.context = new Ctor();
    this.master = this.context.createGain();
    this.master.gain.value = options.volume ?? 0.8;
    this.master.connect(this.context.destination);
  }

  /** Fetch and decode every clip. Safe to call once, at boot. */
  async load(): Promise<void> {
    const names: string[] = [...SINGLE];
    for (const [family, count] of Object.entries(VARIED)) {
      for (let i = 1; i <= count; i += 1) {
        names.push(`${family}_${String(i).padStart(2, "0")}`);
      }
    }

    await Promise.all(
      names.map(async (name) => {
        try {
          const response = await fetch(`${BASE}${name}.mp3`);
          if (!response.ok) return;
          const buffer = await this.context.decodeAudioData(await response.arrayBuffer());
          this.buffers.set(name, buffer);
        } catch {
          // A missing or undecodable clip must never stop the game booting.
          // Silence for one sound is a far better failure than a black screen.
        }
      }),
    );

    this.ready = this.buffers.size > 0;
  }

  /**
   * Resume the context. Must be called from a user gesture.
   *
   * Without this every `play` is a no-op that reports success, which is a
   * genuinely hard bug to spot: nothing throws and nothing logs.
   */
  async unlock(): Promise<void> {
    if (this.context.state === "suspended") await this.context.resume();
  }

  private playBuffer(name: (typeof SINGLE)[number] | string, volume: number, rate: number): void {
    if (!this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get(name);
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = rate;

    const gain = this.context.createGain();
    gain.gain.value = volume;

    source.connect(gain).connect(this.master);
    source.start();
  }

  /**
   * Play a random variation, never the same one twice in a row.
   *
   * Pure random repeats about 1 in `count` times, and a repeated gunshot is
   * the exact artefact variations exist to avoid.
   */
  private playVaried(family: VariedName, volume = 1, rateJitter = 0.06): void {
    const count = VARIED[family];
    const previous = this.lastVariation.get(family) ?? -1;

    let index = 1 + Math.floor(Math.random() * count);
    if (count > 1 && index === previous) index = (index % count) + 1;
    this.lastVariation.set(family, index);

    const rate = 1 + (Math.random() * 2 - 1) * rateJitter;
    this.playBuffer(`${family}_${String(index).padStart(2, "0")}`, volume, rate);
  }

  fire(): void {
    this.playVaried("fire", 0.85, 0.04);
  }

  impact(): void {
    this.playVaried("impact_concrete", 0.6);
  }

  reload(): void {
    this.playBuffer("reload", 0.7, 1);
  }

  ui(kind: "hover" | "click" | "error"): void {
    this.playBuffer(`ui_${kind}`, 0.6, 1);
  }

  /**
   * Advance the footstep cycle.
   *
   * @param distance metres travelled since the last call
   * @param grounded no steps while airborne
   * @param onGrating true when standing on catwalk or gantry decking
   */
  step(distance: number, grounded: boolean, onGrating: boolean): void {
    if (!grounded) {
      // Reset rather than accumulate, so landing does not immediately fire a
      // step from distance covered in the air.
      this.stepAccumulator = 0;
      return;
    }

    this.stepAccumulator += distance;
    if (this.stepAccumulator < STEP_DISTANCE) return;
    this.stepAccumulator -= STEP_DISTANCE;

    this.playVaried(onGrating ? "step_grating" : "step_concrete", 0.5, 0.09);
  }

  startAmbience(): void {
    if (this.ambience || !this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get("ambience_yard");
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.loop = true;

    const gain = this.context.createGain();
    gain.gain.value = 0.0;
    source.connect(gain).connect(this.master);
    source.start();

    // Fade in: the bed appearing at full level the instant a match starts is
    // more noticeable than the silence it replaces.
    gain.gain.linearRampToValueAtTime(0.55, this.context.currentTime + 2.5);
    this.ambience = source;
  }

  setVolume(value: number): void {
    this.master.gain.value = Math.max(0, Math.min(1, value));
  }

  dispose(): void {
    this.ambience?.stop();
    this.ambience = null;
    void this.context.close();
  }
}
