/**
 * Game audio.
 *
 * The build shipped completely silent — no clips, no code. Everything played
 * here is generated by `tools/art/audio/generate.py`; see
 * `apps/game/public/audio/PROVENANCE.md`.
 *
 * Raw Web Audio rather than Babylon's `Sound`: this needs a handful of
 * one-shots, a loop, and a gain trim, and going direct avoids pulling in
 * Babylon's audio engine and its own unlock handling on top of the browser's.
 *
 * Two browser realities shape the design:
 *
 *  1. **Autoplay policy.** An `AudioContext` created before a user gesture
 *     starts suspended, and buffers played into it are silently discarded —
 *     not an error, just nothing. `unlock()` is called from the same gesture
 *     that takes pointer lock.
 *  2. **Decoding is async and not free.** Every clip is fetched and decoded
 *     once up front; triggering a sound mid-match is then a buffer-source
 *     allocation, which is cheap enough to do on every footstep.
 */

import SOUNDTRACK from "virtual:soundtrack";

/** Clip families with variations. Index is 1-based to match the filenames. */
const VARIED = {
  fire: 4,
  step_concrete: 5,
  step_grating: 4,
  impact_concrete: 4,
  explosion: 3,
} as const;

const SINGLE = ["reload", "ui_hover", "ui_click", "ui_error", "ambience_yard"] as const;

/**
 * Background music.
 *
 * Streamed through an `<audio>` element rather than decoded like the effects.
 * These are four-minute tracks at roughly 9 MB each; `decodeAudioData` would
 * pull every one of them into memory as uncompressed PCM — hundreds of
 * megabytes — to play one at a time. An element streams, starts immediately,
 * and is what media playback is for.
 *
 * They are also deliberately excluded from the shell download budget: the game
 * is playable before a note has arrived, so music is fetched on demand rather
 * than gating the first match (PRD §30).
 */
interface Track {
  /** Path under `audio/`, artist folder and all. */
  readonly file: string;
  readonly title: string;
  readonly artist: string;
  /** The album folder, when the track sits in one. */
  readonly album?: string;
}

/**
 * Artist display names, keyed by folder, for a folder that is not already
 * spelt the way the artist writes it.
 *
 * Þrøngva's folder is the artist's own spelling, so it needs no entry: every
 * segment of a track URL is percent-encoded (see `trackUrl`). Anything unlisted
 * falls back to the folder name with its first letter capitalised, so a new
 * artist appears sensibly without an entry.
 */
const ARTIST_NAMES: Record<string, string> = {};

/** An album's track number, `001. ` or `20. `: an ordering, not part of the title. */
const TRACK_NUMBER = /^\d+\.\s*/;

/** Words a title leaves lowercase unless they lead. */
const MINOR_WORDS = new Set(["a", "an", "and", "at", "for", "in", "of", "on", "or", "the", "to"]);

const capitalise = (word: string) => word.charAt(0).toUpperCase() + word.slice(1);

/**
 * Turn a file stem into a display title.
 *
 * `the-wolf-called-want-part-2` -> `The Wolf Called Want (Part 2)`. A stem that
 * already contains spaces is taken as authored, since someone who names a file
 * `More Than Enough.mp3` has already made the decision.
 */
export function titleFromStem(stem: string): string {
  if (stem.includes(" ")) return stem;

  const part = /-part-(\d+)$/i.exec(stem);
  const words = (part ? stem.slice(0, part.index) : stem).split("-").filter(Boolean);
  const title = words
    .map((word, index) =>
      index > 0 && MINOR_WORDS.has(word.toLowerCase()) ? word.toLowerCase() : capitalise(word),
    )
    .join(" ");

  return part ? `${title} (Part ${part[1]})` : title;
}

/**
 * `<artist>/<song>.mp3` or `<artist>/<album>/<song>.mp3`, as the glob emits
 * it, to a playable track.
 */
/**
 * A shuffled play order over `count` tracks: every track once, in random
 * order, before any repeats. `avoidFirst` is the track that just finished, so
 * a reshuffle never plays the same song twice in a row across the boundary.
 */
export function shuffledOrder(
  count: number,
  random: () => number = Math.random,
  avoidFirst?: number,
): number[] {
  const order = Array.from({ length: count }, (_, i) => i);
  for (let i = count - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [order[i], order[j]] = [order[j] as number, order[i] as number];
  }
  if (count > 1 && order[0] === avoidFirst)
    [order[0], order[1]] = [order[1] as number, order[0] as number];
  return order;
}

export function toTrack(relative: string): Track {
  const segments = relative.split("/");
  const folder = segments[0] ?? "";
  const file = segments.at(-1) ?? "";
  const album = segments.length > 2 ? segments.slice(1, -1).join("/") : undefined;
  return {
    file: `music/${relative}`,
    title: titleFromStem(file.replace(/\.mp3$/i, "").replace(TRACK_NUMBER, "")),
    artist: ARTIST_NAMES[folder] ?? capitalise(folder),
    ...(album ? { album } : {}),
  };
}

/**
 * The soundtrack, organised by artist.
 *
 * `music/<artist>/<song>.mp3` rather than a flat `music_*.mp3` pile: the
 * licence and attribution belong to the artist, not to each file, and a folder
 * per artist is where a reader looks for that. It also stopped a real bug —
 * the download-budget guard excluded music by a `^music_` filename pattern,
 * which silently under-counted the moment a track arrived under its own name.
 * A directory cannot be misspelt into the wrong bucket.
 *
 * The list is **discovered, not written down**: `virtual:soundtrack` globs that
 * directory (see `vite-plugin-soundtrack.ts`). Adding a track is dropping the
 * file in — no edit here, and no Blender-dependent `assets:build`.
 */
const MUSIC: readonly Track[] = SOUNDTRACK.map(toTrack);

/**
 * The URL for a track.
 *
 * Each path segment is encoded separately — the separators must survive, but a
 * track named `More Than Enough.mp3` must not reach the network with raw
 * spaces in it. Track names come from a filesystem, so they will not all be
 * tidy kebab-case.
 */
function trackUrl(track: Track): string {
  return BASE + track.file.split("/").map(encodeURIComponent).join("/");
}

type VariedName = keyof typeof VARIED;

const BASE = `${import.meta.env.BASE_URL}audio/`;

/**
 * Metres of travel between footsteps.
 *
 * Driving steps off distance rather than a timer means they automatically
 * speed up when sprinting and stop when the player does, with no state machine
 * and no drift between the sound and the movement the server simulates.
 */
const STEP_DISTANCE = 2.1;

export interface AudioOptions {
  /** Master trim, 0..1. */
  volume?: number;
}

export class GameAudio {
  private readonly context: AudioContext;
  /** Held while a mosquito is audible; see `whine`. */
  private whineVoices: { gain: GainNode; oscillators: OscillatorNode[] } | null = null;
  private readonly master: GainNode;
  private readonly buffers = new Map<string, AudioBuffer>();
  private ambience: AudioBufferSourceNode | null = null;
  private music: HTMLAudioElement | null = null;
  private musicIndex = 0;
  /** What plays after the current track: a shuffle bag over every album. */
  private musicQueue: number[] = [];
  private stepAccumulator = 0;
  /** Squad radio clips, keyed `<side>/<line>`, loaded on first deploy. */
  private readonly radioBuffers = new Map<string, AudioBuffer>();
  private radioBusyUntil = 0;
  private radioLoaded = false;
  private musicVolume = 0.28;
  private lastVariation = new Map<string, number>();
  private ready = false;

  constructor(options: AudioOptions = {}) {
    const Ctor: typeof AudioContext =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
    this.context = new Ctor();
    this.master = this.context.createGain();
    this.master.gain.value = options.volume ?? 0.8;
    this.master.connect(this.context.destination);
  }

  /** Fetch and decode every clip. Safe to call once, at boot. */
  async load(): Promise<void> {
    const names: string[] = [...SINGLE];
    for (const [family, count] of Object.entries(VARIED)) {
      for (let i = 1; i <= count; i += 1) {
        names.push(`${family}_${String(i).padStart(2, "0")}`);
      }
    }

    await Promise.all(
      names.map(async (name) => {
        try {
          const response = await fetch(`${BASE}${name}.mp3`);
          if (!response.ok) return;
          const buffer = await this.context.decodeAudioData(await response.arrayBuffer());
          this.buffers.set(name, buffer);
        } catch {
          // A missing or undecodable clip must never stop the game booting.
          // Silence for one sound is a far better failure than a black screen.
        }
      }),
    );

    this.ready = this.buffers.size > 0;
  }

  /**
   * Resume the context. Must be called from a user gesture.
   *
   * Without this every `play` is a no-op that reports success, which is a
   * genuinely hard bug to spot: nothing throws and nothing logs.
   */
  async unlock(): Promise<void> {
    if (this.context.state === "suspended") await this.context.resume();
  }

  private playBuffer(name: (typeof SINGLE)[number] | string, volume: number, rate: number): void {
    if (!this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get(name);
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = rate;

    const gain = this.context.createGain();
    gain.gain.value = volume;

    source.connect(gain).connect(this.master);
    source.start();
  }

  /**
   * Play a random variation, never the same one twice in a row.
   *
   * Pure random repeats about 1 in `count` times, and a repeated gunshot is
   * the exact artefact variations exist to avoid.
   */
  private playVaried(family: VariedName, volume = 1, rateJitter = 0.06): void {
    const count = VARIED[family];
    const previous = this.lastVariation.get(family) ?? -1;

    let index = 1 + Math.floor(Math.random() * count);
    if (count > 1 && index === previous) index = (index % count) + 1;
    this.lastVariation.set(family, index);

    const rate = 1 + (Math.random() * 2 - 1) * rateJitter;
    this.playBuffer(`${family}_${String(index).padStart(2, "0")}`, volume, rate);
  }

  fire(): void {
    this.playVaried("fire", 0.85, 0.04);
  }

  impact(): void {
    this.playVaried("impact_concrete", 0.6);
  }

  /**
   * A grenade detonating, at a volume set by how far away it was.
   *
   * Distance attenuation is done here rather than with a positional audio node
   * because there is exactly one listener and the clip is a one-shot; a full
   * panner graph per explosion buys nothing a curve does not. The floor is
   * deliberately non-zero — a blast you cannot hear is a blast you cannot
   * learn from.
   */
  explosion(distanceM = 0): void {
    const falloff = Math.max(0.16, 1 - distanceM / 42);
    // Larger jitter than a gunshot: three takes have to cover a whole match.
    this.playVaried("explosion", falloff, 0.09);
  }

  reload(): void {
    this.playBuffer("reload", 0.7, 1);
  }

  /**
   * Taking a hit: a short thump low under the ear.
   *
   * Synthesised rather than sampled. There is no recorded hurt sound in the
   * set, and a grunt would need a voice and a licence; a pitch-dropping sine
   * is a body blow every player already reads without one.
   */
  hurt(): void {
    if (this.context.state !== "running") return;
    const now = this.context.currentTime;
    const osc = this.context.createOscillator();
    osc.type = "sine";
    osc.frequency.setValueAtTime(110, now);
    osc.frequency.exponentialRampToValueAtTime(38, now + 0.16);
    const gain = this.context.createGain();
    gain.gain.setValueAtTime(0.0001, now);
    gain.gain.exponentialRampToValueAtTime(0.7, now + 0.012);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.2);
    osc.connect(gain).connect(this.master);
    osc.start(now);
    osc.stop(now + 0.22);
  }

  /** Picking something up: two quick rising blips. Synthesised, as above. */
  pickup(): void {
    if (this.context.state !== "running") return;
    const now = this.context.currentTime;
    [660, 990].forEach((frequency, i) => {
      const at = now + i * 0.075;
      const osc = this.context.createOscillator();
      osc.type = "triangle";
      osc.frequency.setValueAtTime(frequency, at);
      const gain = this.context.createGain();
      gain.gain.setValueAtTime(0.0001, at);
      gain.gain.exponentialRampToValueAtTime(0.35, at + 0.008);
      gain.gain.exponentialRampToValueAtTime(0.0001, at + 0.07);
      osc.connect(gain).connect(this.master);
      osc.start(at);
      osc.stop(at + 0.08);
    });
  }

  /**
   * The mosquito's whine, held while one is near and faded out when it leaves.
   *
   * Synthesised for the same reason `hurt` is: there is no recorded whine in
   * the set, and this one suits synthesis better than most — a female Culicid
   * wingbeat really is a narrow tone near 600 Hz, so an oscillator is closer
   * to the real thing than a sample would be.
   *
   * Two detuned saws a few Hz apart give the beating, wavering quality that
   * makes it read as an insect rather than a test tone. `nearness` is 0 when
   * it is across the yard and 1 when it is at the ear; it drives gain and a
   * little pitch, so the approach is audible before it is visible.
   *
   * Call every frame it is wanted and `stopWhine` when it is not. Starting an
   * oscillator per frame would click; this keeps one alive and rides the gain.
   */
  whine(nearness: number): void {
    if (this.context.state !== "running") return;
    const now = this.context.currentTime;
    const level = Math.max(0, Math.min(1, nearness));

    if (!this.whineVoices) {
      const gain = this.context.createGain();
      gain.gain.value = 0.0001;
      gain.connect(this.master);
      const oscillators = [0, 5.5].map((detune) => {
        const osc = this.context.createOscillator();
        osc.type = "sawtooth";
        osc.frequency.value = 610 + detune;
        // A gentle low-pass keeps the saw from being a buzzsaw: the whine is
        // thin and nasal, not harsh.
        const tone = this.context.createBiquadFilter();
        tone.type = "lowpass";
        tone.frequency.value = 2400;
        osc.connect(tone).connect(gain);
        osc.start(now);
        return osc;
      });
      this.whineVoices = { gain, oscillators };
    }

    const { gain, oscillators } = this.whineVoices;
    // Pitch rises slightly as it closes, the way a passing insect does.
    oscillators.forEach((osc, i) => {
      osc.frequency.setTargetAtTime(590 + i * 5.5 + level * 70, now, 0.08);
    });
    gain.gain.setTargetAtTime(Math.max(0.0001, level * 0.18), now, 0.05);
  }

  /** Fade the whine out and release its oscillators. */
  stopWhine(): void {
    const voices = this.whineVoices;
    if (!voices) return;
    this.whineVoices = null;
    const now = this.context.currentTime;
    voices.gain.gain.setTargetAtTime(0.0001, now, 0.06);
    for (const osc of voices.oscillators) osc.stop(now + 0.4);
  }

  ui(kind: "hover" | "click" | "error"): void {
    this.playBuffer(`ui_${kind}`, 0.6, 1);
  }

  /**
   * Advance the footstep cycle.
   *
   * @param distance metres travelled since the last call
   * @param grounded no steps while airborne
   * @param onGrating true when standing on catwalk or gantry decking
   */
  step(distance: number, grounded: boolean, onGrating: boolean): void {
    if (!grounded) {
      // Reset rather than accumulate, so landing does not immediately fire a
      // step from distance covered in the air.
      this.stepAccumulator = 0;
      return;
    }

    this.stepAccumulator += distance;
    if (this.stepAccumulator < STEP_DISTANCE) return;
    this.stepAccumulator -= STEP_DISTANCE;

    this.playVaried(onGrating ? "step_grating" : "step_concrete", 0.5, 0.09);
  }

  startAmbience(): void {
    if (this.ambience || !this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get("ambience_yard");
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.loop = true;

    const gain = this.context.createGain();
    gain.gain.value = 0.0;
    source.connect(gain).connect(this.master);
    source.start();

    // Fade in: the bed appearing at full level the instant a match starts is
    // more noticeable than the silence it replaces.
    gain.gain.linearRampToValueAtTime(0.55, this.context.currentTime + 2.5);
    this.ambience = source;
  }

  /**
   * Start the soundtrack, shuffled across every album, advancing to another
   * random track on end.
   *
   * Quiet by default. This sits under gunfire and footsteps, and music that
   * competes with the audio cues a player needs is worse than silence.
   */
  startMusic(volume = 0.28): void {
    if (this.music) return;
    // No soundtrack shipped: nothing to start, and `advance` would divide by
    // zero and loop on a blank src forever.
    if (MUSIC.length === 0) return;

    // A random song from any album, then more random songs: a shuffle bag, so
    // every track plays once before any repeats and none plays twice running.
    this.musicQueue = shuffledOrder(MUSIC.length);
    this.musicIndex = this.musicQueue.shift() ?? 0;
    const element = new Audio();
    this.musicVolume = volume;
    element.volume = volume;
    element.preload = "none";

    const play = (track: Track | undefined) => {
      if (!track) return;
      element.src = trackUrl(track);
      void element.play().catch(() => {
        // Autoplay can still be refused; failing quietly is right here,
        // because losing the soundtrack must never interrupt a match.
      });
    };

    const advance = () => {
      if (this.musicQueue.length === 0)
        this.musicQueue = shuffledOrder(MUSIC.length, Math.random, this.musicIndex);
      this.musicIndex = this.musicQueue.shift() ?? 0;
      play(MUSIC[this.musicIndex]);
    };

    element.addEventListener("ended", advance);
    // A track that fails to load should move on rather than end the playlist.
    element.addEventListener("error", advance);

    play(MUSIC[this.musicIndex]);
    this.music = element;
  }

  /**
   * Fetch and decode one side's squad radio. Called after the first deploy,
   * not at boot: 60 short clips are not worth delaying the first frame for,
   * and a transmission that has not loaded yet is simply not heard.
   */
  async loadRadio(side: string, lines: readonly string[]): Promise<void> {
    await Promise.all(
      lines.map(async (line) => {
        const key = `${side}/${line}`;
        if (this.radioBuffers.has(key)) return;
        try {
          const response = await fetch(`${BASE}comms/${side}/${line}.mp3`);
          if (!response.ok) return;
          this.radioBuffers.set(
            key,
            await this.context.decodeAudioData(await response.arrayBuffer()),
          );
        } catch {
          // A missing line is a gap on the net, never a failure.
        }
      }),
    );
    this.radioLoaded = this.radioBuffers.size > 0;
  }

  /** True once the squad radio has loaded; before that there is nothing to key up. */
  radioReady(): boolean {
    return this.radioLoaded;
  }

  /** True while a transmission is still playing. */
  radioBusy(): boolean {
    return this.context.currentTime < this.radioBusyUntil;
  }

  /**
   * Key up: play the clips back to back as one transmission (a callsign then
   * its order), dipping the music under the voice. Chatter sits lower than
   * callouts and orders, so the net can murmur without covering anything.
   */
  transmit(side: string, lines: readonly string[], kind: "callout" | "order" | "chatter"): void {
    if (this.context.state !== "running") return;
    const buffers = lines
      .map((line) => this.radioBuffers.get(`${side}/${line}`))
      .filter((b): b is AudioBuffer => Boolean(b));
    if (buffers.length === 0) return;

    const level = kind === "chatter" ? 0.42 : kind === "order" ? 0.8 : 0.9;
    let at = Math.max(this.context.currentTime + 0.02, this.radioBusyUntil);
    for (const buffer of buffers) {
      const source = this.context.createBufferSource();
      source.buffer = buffer;
      const gain = this.context.createGain();
      gain.gain.value = level;
      source.connect(gain).connect(this.master);
      source.start(at);
      at += buffer.duration;
    }
    this.radioBusyUntil = at;

    // Duck the soundtrack for the length of the transmission, then bring it back.
    if (this.music && kind !== "chatter") {
      const element = this.music;
      element.volume = this.musicVolume * 0.45;
      window.setTimeout(
        () => {
          if (this.context.currentTime >= this.radioBusyUntil - 0.05)
            element.volume = this.musicVolume;
        },
        (at - this.context.currentTime + 0.1) * 1000,
      );
    }
  }

  /** The track playing now, for a "now playing" line if one is ever wanted. */
  nowPlaying(): Track | undefined {
    return this.music ? MUSIC[this.musicIndex] : undefined;
  }

  stopMusic(): void {
    this.music?.pause();
    this.music = null;
  }

  setMusicVolume(value: number): void {
    this.musicVolume = Math.max(0, Math.min(1, value));
    if (this.music) this.music.volume = this.musicVolume;
  }

  setVolume(value: number): void {
    this.master.gain.value = Math.max(0, Math.min(1, value));
  }

  dispose(): void {
    this.stopMusic();
    this.ambience?.stop();
    this.ambience = null;
    void this.context.close();
  }
}
