/**
 * Game audio.
 *
 * The build shipped completely silent — no clips, no code. Everything played
 * here is generated by `tools/art/audio/generate.py`; see
 * `apps/game/public/audio/PROVENANCE.md`.
 *
 * Raw Web Audio rather than Babylon's `Sound`: this needs a handful of
 * one-shots, a loop, and a gain trim, and going direct avoids pulling in
 * Babylon's audio engine and its own unlock handling on top of the browser's.
 *
 * Two browser realities shape the design:
 *
 *  1. **Autoplay policy.** An `AudioContext` created before a user gesture
 *     starts suspended, and buffers played into it are silently discarded —
 *     not an error, just nothing. `unlock()` is called from the same gesture
 *     that takes pointer lock.
 *  2. **Decoding is async and not free.** Every clip is fetched and decoded
 *     once up front; triggering a sound mid-match is then a buffer-source
 *     allocation, which is cheap enough to do on every footstep.
 */

import SOUNDTRACK from "virtual:soundtrack";

/** Clip families with variations. Index is 1-based to match the filenames. */
const VARIED = {
  fire: 4,
  step_concrete: 5,
  step_grating: 4,
  impact_concrete: 4,
  explosion: 3,
} as const;

const SINGLE = ["reload", "ui_hover", "ui_click", "ui_error", "ambience_yard"] as const;

/**
 * Background music.
 *
 * Streamed through an `<audio>` element rather than decoded like the effects.
 * These are four-minute tracks at roughly 9 MB each; `decodeAudioData` would
 * pull every one of them into memory as uncompressed PCM — hundreds of
 * megabytes — to play one at a time. An element streams, starts immediately,
 * and is what media playback is for.
 *
 * They are also deliberately excluded from the shell download budget: the game
 * is playable before a note has arrived, so music is fetched on demand rather
 * than gating the first match (PRD §30).
 */
interface Track {
  /** Path under `audio/`, artist folder and all. */
  readonly file: string;
  readonly title: string;
  readonly artist: string;
}

/**
 * Artist display names, keyed by folder.
 *
 * The folder is ASCII so it is safe in a URL and a shell; the display name is
 * how the artist actually writes it. Anything unlisted falls back to the folder
 * name in title case, so a new artist appears sensibly without an entry.
 */
const ARTIST_NAMES: Record<string, string> = {
  throngva: "Þrøngva",
};

/** Words a title leaves lowercase unless they lead. */
const MINOR_WORDS = new Set(["a", "an", "and", "at", "for", "in", "of", "on", "or", "the", "to"]);

const capitalise = (word: string) => word.charAt(0).toUpperCase() + word.slice(1);

/**
 * Turn a file stem into a display title.
 *
 * `the-wolf-called-want-part-2` -> `The Wolf Called Want (Part 2)`. A stem that
 * already contains spaces is taken as authored, since someone who names a file
 * `More Than Enough.mp3` has already made the decision.
 */
export function titleFromStem(stem: string): string {
  if (stem.includes(" ")) return stem;

  const part = /-part-(\d+)$/i.exec(stem);
  const words = (part ? stem.slice(0, part.index) : stem).split("-").filter(Boolean);
  const title = words
    .map((word, index) =>
      index > 0 && MINOR_WORDS.has(word.toLowerCase()) ? word.toLowerCase() : capitalise(word),
    )
    .join(" ");

  return part ? `${title} (Part ${part[1]})` : title;
}

/** `<artist>/<song>.mp3`, as the glob emits it, to a playable track. */
export function toTrack(relative: string): Track {
  const [folder = "", file = ""] = relative.split("/");
  return {
    file: `music/${relative}`,
    title: titleFromStem(file.replace(/\.mp3$/i, "")),
    artist: ARTIST_NAMES[folder] ?? capitalise(folder),
  };
}

/**
 * The soundtrack, organised by artist.
 *
 * `music/<artist>/<song>.mp3` rather than a flat `music_*.mp3` pile: the
 * licence and attribution belong to the artist, not to each file, and a folder
 * per artist is where a reader looks for that. It also stopped a real bug —
 * the download-budget guard excluded music by a `^music_` filename pattern,
 * which silently under-counted the moment a track arrived under its own name.
 * A directory cannot be misspelt into the wrong bucket.
 *
 * The list is **discovered, not written down**: `virtual:soundtrack` globs that
 * directory (see `vite-plugin-soundtrack.ts`). Adding a track is dropping the
 * file in — no edit here, and no Blender-dependent `assets:build`.
 */
const MUSIC: readonly Track[] = SOUNDTRACK.map(toTrack);

/**
 * The URL for a track.
 *
 * Each path segment is encoded separately — the separators must survive, but a
 * track named `More Than Enough.mp3` must not reach the network with raw
 * spaces in it. Track names come from a filesystem, so they will not all be
 * tidy kebab-case.
 */
function trackUrl(track: Track): string {
  return BASE + track.file.split("/").map(encodeURIComponent).join("/");
}

type VariedName = keyof typeof VARIED;

const BASE = `${import.meta.env.BASE_URL}audio/`;

/**
 * Metres of travel between footsteps.
 *
 * Driving steps off distance rather than a timer means they automatically
 * speed up when sprinting and stop when the player does, with no state machine
 * and no drift between the sound and the movement the server simulates.
 */
const STEP_DISTANCE = 2.1;

export interface AudioOptions {
  /** Master trim, 0..1. */
  volume?: number;
}

export class GameAudio {
  private readonly context: AudioContext;
  private readonly master: GainNode;
  private readonly buffers = new Map<string, AudioBuffer>();
  private ambience: AudioBufferSourceNode | null = null;
  private music: HTMLAudioElement | null = null;
  private musicIndex = 0;
  private stepAccumulator = 0;
  private lastVariation = new Map<string, number>();
  private ready = false;

  constructor(options: AudioOptions = {}) {
    const Ctor: typeof AudioContext =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
    this.context = new Ctor();
    this.master = this.context.createGain();
    this.master.gain.value = options.volume ?? 0.8;
    this.master.connect(this.context.destination);
  }

  /** Fetch and decode every clip. Safe to call once, at boot. */
  async load(): Promise<void> {
    const names: string[] = [...SINGLE];
    for (const [family, count] of Object.entries(VARIED)) {
      for (let i = 1; i <= count; i += 1) {
        names.push(`${family}_${String(i).padStart(2, "0")}`);
      }
    }

    await Promise.all(
      names.map(async (name) => {
        try {
          const response = await fetch(`${BASE}${name}.mp3`);
          if (!response.ok) return;
          const buffer = await this.context.decodeAudioData(await response.arrayBuffer());
          this.buffers.set(name, buffer);
        } catch {
          // A missing or undecodable clip must never stop the game booting.
          // Silence for one sound is a far better failure than a black screen.
        }
      }),
    );

    this.ready = this.buffers.size > 0;
  }

  /**
   * Resume the context. Must be called from a user gesture.
   *
   * Without this every `play` is a no-op that reports success, which is a
   * genuinely hard bug to spot: nothing throws and nothing logs.
   */
  async unlock(): Promise<void> {
    if (this.context.state === "suspended") await this.context.resume();
  }

  private playBuffer(name: (typeof SINGLE)[number] | string, volume: number, rate: number): void {
    if (!this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get(name);
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.playbackRate.value = rate;

    const gain = this.context.createGain();
    gain.gain.value = volume;

    source.connect(gain).connect(this.master);
    source.start();
  }

  /**
   * Play a random variation, never the same one twice in a row.
   *
   * Pure random repeats about 1 in `count` times, and a repeated gunshot is
   * the exact artefact variations exist to avoid.
   */
  private playVaried(family: VariedName, volume = 1, rateJitter = 0.06): void {
    const count = VARIED[family];
    const previous = this.lastVariation.get(family) ?? -1;

    let index = 1 + Math.floor(Math.random() * count);
    if (count > 1 && index === previous) index = (index % count) + 1;
    this.lastVariation.set(family, index);

    const rate = 1 + (Math.random() * 2 - 1) * rateJitter;
    this.playBuffer(`${family}_${String(index).padStart(2, "0")}`, volume, rate);
  }

  fire(): void {
    this.playVaried("fire", 0.85, 0.04);
  }

  impact(): void {
    this.playVaried("impact_concrete", 0.6);
  }

  /**
   * A grenade detonating, at a volume set by how far away it was.
   *
   * Distance attenuation is done here rather than with a positional audio node
   * because there is exactly one listener and the clip is a one-shot; a full
   * panner graph per explosion buys nothing a curve does not. The floor is
   * deliberately non-zero — a blast you cannot hear is a blast you cannot
   * learn from.
   */
  explosion(distanceM = 0): void {
    const falloff = Math.max(0.16, 1 - distanceM / 42);
    // Larger jitter than a gunshot: three takes have to cover a whole match.
    this.playVaried("explosion", falloff, 0.09);
  }

  reload(): void {
    this.playBuffer("reload", 0.7, 1);
  }

  ui(kind: "hover" | "click" | "error"): void {
    this.playBuffer(`ui_${kind}`, 0.6, 1);
  }

  /**
   * Advance the footstep cycle.
   *
   * @param distance metres travelled since the last call
   * @param grounded no steps while airborne
   * @param onGrating true when standing on catwalk or gantry decking
   */
  step(distance: number, grounded: boolean, onGrating: boolean): void {
    if (!grounded) {
      // Reset rather than accumulate, so landing does not immediately fire a
      // step from distance covered in the air.
      this.stepAccumulator = 0;
      return;
    }

    this.stepAccumulator += distance;
    if (this.stepAccumulator < STEP_DISTANCE) return;
    this.stepAccumulator -= STEP_DISTANCE;

    this.playVaried(onGrating ? "step_grating" : "step_concrete", 0.5, 0.09);
  }

  startAmbience(): void {
    if (this.ambience || !this.ready || this.context.state !== "running") return;
    const buffer = this.buffers.get("ambience_yard");
    if (!buffer) return;

    const source = this.context.createBufferSource();
    source.buffer = buffer;
    source.loop = true;

    const gain = this.context.createGain();
    gain.gain.value = 0.0;
    source.connect(gain).connect(this.master);
    source.start();

    // Fade in: the bed appearing at full level the instant a match starts is
    // more noticeable than the silence it replaces.
    gain.gain.linearRampToValueAtTime(0.55, this.context.currentTime + 2.5);
    this.ambience = source;
  }

  /**
   * Start the soundtrack, shuffled, advancing to the next track on end.
   *
   * Quiet by default. This sits under gunfire and footsteps, and music that
   * competes with the audio cues a player needs is worse than silence.
   */
  startMusic(volume = 0.28): void {
    if (this.music) return;
    // No soundtrack shipped: nothing to start, and `advance` would divide by
    // zero and loop on a blank src forever.
    if (MUSIC.length === 0) return;

    this.musicIndex = Math.floor(Math.random() * MUSIC.length);
    const element = new Audio();
    element.volume = volume;
    element.preload = "none";

    const play = (track: Track | undefined) => {
      if (!track) return;
      element.src = trackUrl(track);
      void element.play().catch(() => {
        // Autoplay can still be refused; failing quietly is right here,
        // because losing the soundtrack must never interrupt a match.
      });
    };

    const advance = () => {
      this.musicIndex = (this.musicIndex + 1) % MUSIC.length;
      play(MUSIC[this.musicIndex]);
    };

    element.addEventListener("ended", advance);
    // A track that fails to load should move on rather than end the playlist.
    element.addEventListener("error", advance);

    play(MUSIC[this.musicIndex]);
    this.music = element;
  }

  /** The track playing now, for a "now playing" line if one is ever wanted. */
  nowPlaying(): Track | undefined {
    return this.music ? MUSIC[this.musicIndex] : undefined;
  }

  stopMusic(): void {
    this.music?.pause();
    this.music = null;
  }

  setMusicVolume(value: number): void {
    if (this.music) this.music.volume = Math.max(0, Math.min(1, value));
  }

  setVolume(value: number): void {
    this.master.gain.value = Math.max(0, Math.min(1, value));
  }

  dispose(): void {
    this.stopMusic();
    this.ambience?.stop();
    this.ambience = null;
    void this.context.close();
  }
}
