import manifest from "../public/media/art/manifest.json";
import { ClickableGallery } from "./_components/clickable-gallery";
import { ClickableSheet } from "./_components/clickable-figures";
import type { LightboxShot } from "./_components/lightbox";

/**
 * The current art pass, and the build it produced.
 *
 * Two different claims, kept apart on purpose:
 *
 * - the **asset sheet** is what was modelled — every tile is a render of a
 *   `.glb` that ships in `apps/game/public/assets/models/`, one for one;
 * - the **gameplay frames** are what that geometry looks like in play, with
 *   the operators, the weapons and the HUD in frame.
 *
 * Neither is concept art, and the copy never says "art" without saying which
 * of the two it means. Same rule as `gallery.tsx`: the numbers come from the
 * manifest, so a new art pass updates the page rather than the prose.
 */

const SHEET = manifest.assetSheet;
const FRAMES = manifest.frames;

/** Shots carry their own media directory (see `captureSrc`). */
const SHEET_SHOT: LightboxShot = {
  name: "asset-sheet",
  caption: SHEET.subtitle,
  file: SHEET.file,
  dir: "art",
};

const FRAME_SHOTS: LightboxShot[] = FRAMES.shots.map((shot) => ({ ...shot, dir: "art" }));

/** One-line summary of the current pass, for a section lede. */
export const SHEET_SUMMARY = `All ${SHEET.models} production models in the build come from the ${SHEET.title} pass — original geometry, rigged and exported as glTF.`;

/** The four gameplay frames — the operators and the HUD, not empty geometry. */
export function GameplayFrames() {
  return (
    <>
      <ClickableGallery shots={FRAME_SHOTS} width={FRAMES.width} height={FRAMES.height} />
      <p className="gallery__note">
        Captured from the playable build at {FRAMES.width}&times;{FRAMES.height} by{" "}
        <code>{FRAMES.tool}</code>, which drives the real game rather than posing a scene. Click any
        frame to view it full size.
      </p>
    </>
  );
}

/** The contact sheet of every model in the build. */
export function AssetSheet() {
  return (
    <>
      <ClickableSheet
        shot={SHEET_SHOT}
        label={`${SHEET.title} · ${SHEET.models} models · ${SHEET.date}`}
        width={SHEET.width}
        height={SHEET.height}
      />
      <p className="gallery__note">
        Every tile is a render of the exported file, not a concept sketch: the sheet matches{" "}
        <code>apps/game/public/assets/models/</code> one for one, triangle counts included. Original
        geometry, generated by <code>{SHEET.generator}</code>. Open it to read the labels.
      </p>
    </>
  );
}
