const FILMS = [
  { name: "Saffron Freight", directory: "saffron", id: "saffron_freight" },
  { name: "Nacre Relay", directory: "nacre", id: "nacre_relay" },
] as const;

/** Thirty seconds of actual bot-match gameplay per yard; files and poster
 * frames are generated by tools/art/trailer.mjs alongside provenance manifests. */
export function YardFilms() {
  return (
    <div className="yard-showcase">
      {FILMS.map((film) => {
        const base = `/media/yard-films/${film.directory}/${film.id}`;
        return (
          <figure className="film" key={film.id}>
            <video
              className="film__video"
              controls
              preload="none"
              playsInline
              width={1280}
              height={720}
              poster={`${base}-poster.webp`}
              aria-label={`${film.name}: 30 seconds of gameplay`}
            >
              <source src={`${base}-gameplay.mp4`} type="video/mp4" />
              <p>
                <a href={`${base}-gameplay.mp4`} download>
                  Download {film.name} gameplay
                </a>
              </p>
            </video>
            <figcaption>
              <span className="film__label">{film.name} · 30 seconds · Bot deathmatch</span>
              <span>
                In-game movement and combat, with the NIGHTCELL 7 soundtrack and yard ambience.
              </span>
            </figcaption>
            <p>
              <a href={`${base}-gameplay.mp4`} download>
                Download the gameplay clip
              </a>
            </p>
          </figure>
        );
      })}
    </div>
  );
}
