import saffron from "../public/media/yard-films/saffron/manifest.json";
import nacre from "../public/media/yard-films/nacre/manifest.json";
const FILMS = [
  { ...saffron, name: "Saffron Freight", directory: "saffron", id: "saffron_freight" },
  { ...nacre, name: "Nacre Relay", directory: "nacre", id: "nacre_relay" },
] as const;

/** Thirty seconds of actual bot-match gameplay per yard; files and poster
 * frames are generated by tools/art/trailer.mjs alongside provenance manifests. */
export function YardFilms() {
  return (
    <div className="yard-showcase">
      {FILMS.map((film) => {
        const base = `/media/yard-films/${film.directory}`;
        return (
          <figure className="film" key={film.id}>
            <video
              className="film__video"
              controls
              preload="none"
              playsInline
              width={film.width}
              height={film.height}
              poster={`${base}/${film.poster}`}
              aria-label={`${film.name}: ${film.seconds} seconds of gameplay`}
            >
              <source src={`${base}/${film.file}`} type="video/mp4" />
              <p>
                <a href={`${base}/${film.file}`} download>
                  Download {film.name} gameplay
                </a>
              </p>
            </video>
            <figcaption>
              <span className="film__label">
                {film.name} · {film.seconds} seconds · Bot deathmatch
              </span>
              <span>
                In-game movement and combat. Music: “Ironwood Oath” by Þrøngva, with yard ambience.
              </span>
            </figcaption>
            <p>
              <a href={`${base}/${film.file}`} download>
                Download the gameplay clip
              </a>
            </p>
          </figure>
        );
      })}
    </div>
  );
}
