import type { Metadata } from "next";
import { PageShell } from "../_components/page-shell";
import { CapturePlate } from "../gallery";

export const metadata: Metadata = {
  title: "Careers",
  description:
    "Open roles on NIGHTCELL 7. Remote from anywhere, equity-only while the game is pre-revenue.",
};

/**
 * Careers.
 *
 * The compensation terms are stated in the first line of the role rather than
 * buried at the bottom. Equity-only is a real constraint and an artist deserves
 * to know before they read a spec and write an application — burying it wastes
 * their time and earns a reputation we would rather not have.
 */
export default function CareersPage() {
  const mailto = "mailto:careers@nightcell7.com?subject=artist+application";

  return (
    <PageShell
      label="Careers"
      title="Work on NIGHTCELL 7"
      lede="A small team building a two-campaign tactical shooter and a free multiplayer alpha. Remote from wherever you are."
    >
      <h3>Gameplay Graphics Artist</h3>

      <p className="notice">
        <strong>Equity-only for now.</strong> The game is pre-revenue and there is no salary on
        offer. You would be taking equity in exchange for your work, which is a real risk and may be
        worth nothing. If that does not suit you, it does not suit you — no hard feelings, and
        please do not apply expecting it to change.
      </p>

      <h4>What you would own</h4>
      <ul>
        <li>
          Characters and animation — the weakest part of the game today, and the most visible.
        </li>
        <li>
          Weapons, props and set dressing for Ardavan Yard and the Episode 1 campaign locations.
        </li>
        <li>
          Lighting and material direction. The renderer is Babylon.js with a PBR pipeline,
          image-based lighting and a full post stack; the art direction is in place, the execution
          needs someone better than a script.
        </li>
        <li>
          Deciding what is authored by hand and what stays procedural. Every asset in the game is
          currently generated by committed Blender and numpy scripts — that pipeline is yours to
          keep, extend or replace.
        </li>
      </ul>

      <h4>What we are looking for</h4>
      <ul>
        <li>A portfolio of real-time game art. We care about what shipped, not what rendered.</li>
        <li>Blender, or a willingness to work in it — the whole pipeline is Blender and glTF.</li>
        <li>
          Comfort with PBR: albedo, normal, roughness, metallic, and why a material that looks right
          in a viewport can look wrong in an engine.
        </li>
        <li>Character work and rigging is the biggest gap, so that is the strongest signal.</li>
        <li>
          <strong>Fluent English.</strong> The team is distributed and asynchronous, so almost
          everything is written.
        </li>
      </ul>

      <h4>How we work</h4>
      <ul>
        <li>Remote, from wherever you are. No fixed hours, no standups.</li>
        <li>One repository. Art, engine, site and infrastructure ship in the same commit.</li>
        <li>
          Every asset needs provenance — where it came from and under what licence. Bought,
          commissioned and generated are all fine; unattributed is not.
        </li>
      </ul>

      <h4>Apply</h4>
      <p>
        Send a portfolio link and a couple of lines about what you would fix first. No cover letter
        needed.
      </p>
      <p className="cta-row">
        <a className="button button--primary" href={mailto}>
          Email careers@nightcell7.com
        </a>
      </p>
      <p>
        Or write directly to <a href={mailto}>careers@nightcell7.com</a>.
      </p>

      <CapturePlate name="container-alley" label="Ardavan Yard" />
    </PageShell>
  );
}
