import type { Metadata } from "next";
import { PageShell, DraftNotice } from "../_components/page-shell";

export const metadata: Metadata = { title: "Licenses" };

const STACK = [
  ["Babylon.js", "Apache-2.0", "Rendering, scene graph and client physics"],
  ["Colyseus", "MIT", "Authoritative multiplayer rooms and state sync"],
  ["Next.js", "MIT", "This website"],
  ["React", "MIT", "Site and in-game menus"],
  ["Hono", "MIT", "HTTP API"],
  ["Drizzle ORM", "Apache-2.0", "Database schema and queries"],
  ["libSQL / Turso client", "MIT", "Durable data"],
  ["BullMQ", "MIT", "Background jobs"],
  ["ioredis", "MIT", "Redis client"],
  ["Zod", "MIT", "Runtime validation"],
  ["Vite", "MIT", "Game build"],
  ["Electron", "MIT", "Desktop wrapper"],
];

export default function LicensesPage() {
  return (
    <PageShell
      label="Legal"
      title="Licenses and attribution"
      lede="Everything the game and this site are built on."
    >
      <h3>Open-source dependencies</h3>
      <table className="table">
        <thead>
          <tr>
            <th>Project</th>
            <th>License</th>
            <th>Used for</th>
          </tr>
        </thead>
        <tbody>
          {STACK.map(([name, license, use]) => (
            <tr key={name}>
              <td>{name}</td>
              <td>{license}</td>
              <td>{use}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p>
        The full dependency tree with exact versions is in the{" "}
        <a
          href="https://github.com/profullstack/nightcell7"
          target="_blank"
          rel="noopener noreferrer"
        >
          public repository
        </a>
        .
      </p>

      <h3>Game assets</h3>
      <p>
        Every image currently on this site is an in-engine capture of our own geometry, generated by
        a tool in the repository and shipped with a provenance manifest recording the commit it came
        from. There are no third-party art assets in the build yet.
      </p>
      <DraftNotice>
        As external art, audio and voice work enter the project, each item must carry source,
        provider, licence snapshot, commercial and modification rights, browser-distribution rights,
        attribution requirements and a named reviewer before it can ship. That register will be
        published here.
      </DraftNotice>

      <h3>Fonts</h3>
      <p>
        The site currently uses system font stacks. Licensed display and Persian typefaces are
        pending selection and will be listed here once self-hosted.
      </p>
    </PageShell>
  );
}
